version: '2.0'

services:
  wms-viewer:
    image: 'shookas/wms-viewer'
    ports:
      - 4200:80
    restart: always
  geoserver:
    image: 'kartoza/geoserver:2.18.2'
    ports:
      - 8080:8080
    restart: always
    volumes:
      - $HOME/geoserver_data:/opt/geoserver/data_dir
